export const wishes = [
  "May your day be filled with unexpected joy and delightful surprises.",
  "Wishing you the courage to chase your dreams and the wisdom to enjoy the journey.",
  "May you find beauty in the ordinary moments and magic in the mundane.",
  "Hope today brings you closer to your goals and fills your heart with gratitude.",
  "Wishing you strength to overcome challenges and grace to celebrate victories.",
  "May your coffee be strong and your Monday be short.",
  "Hope you find reasons to smile and people to share them with.",
  "Wishing you clarity in confusion and peace in chaos.",
  "May you be blessed with good health, great friends, and endless possibilities.",
  "Hope today treats you with kindness and tomorrow brings even better things.",
  "Wishing you the perfect balance of productivity and relaxation.",
  "May you encounter kindness wherever you go and spread it wherever you've been.",
  "Hope you find time for the things that make your soul happy.",
  "Wishing you moments that take your breath away and people who help you catch it.",
  "May today be the start of something wonderful in your life.",
  "Hope you laugh until you cry and love until it hurts.",
  "Wishing you the wisdom to know when to hold on and when to let go.",
  "May you find inspiration in unexpected places and motivation in everyday things.",
  "Hope you make memories that last a lifetime and stories worth telling.",
  "Wishing you peace in your heart, success in your endeavors, and joy in your journey.",
  "May you be surrounded by people who lift you up and experiences that shape you.",
  "Hope you find your passion and have the courage to pursue it.",
  "Wishing you sunny days, starry nights, and everything in between.",
  "May you always have enough happiness to keep you sweet, enough trials to keep you strong, and enough hope to keep you going.",
  "Hope you dance in the rain and sing in the shower like nobody's watching.",
  "Wishing you the ability to see the good in every situation and the strength to create good where none exists.",
  "May you find comfort in difficult times and celebration in joyous ones.",
  "Hope you learn something new, teach something valuable, and love someone deeply.",
  "Wishing you the perfect day – not because everything goes right, but because you handle whatever comes with grace.",
  "May you be exactly where you need to be, doing exactly what you need to be doing."
];